# File: templates/build-preview.yml

parameters:
  BuildConfiguration: ''
  Arguments: ''
  VmImage: ''
  OS: 'Windows'

jobs:

- job:
  displayName: Preview Flag ${{ parameters.BuildConfiguration }} 
  pool:
    vmImage: ${{ parameters.VmImage }}

  steps:
  - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
    clean: true  # if true, execute `execute git clean -ffdx && git reset --hard HEAD` before fetching

  - task: DotNetCoreCLI@2
    displayName: Build Microsoft.Azure.Cosmos PREVIEW
    inputs: 
      command: build  
      configuration: $(parameters.BuildConfiguration)
      nugetConfigPath: NuGet.config
      projects: Microsoft.Azure.Cosmos.sln 
      arguments: -p:Optimize=true -p:IsPreview=true
      versioningScheme: OFF
      
