name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: morrisoncole/pr-lint-action@master
      with:
        title-regex: '(\[Internal\]|\[v4\] )?.{3}.+: (Add|Fix|Refactor) .{3}.+'
        on-failed-regex-comment: >
         Please follow the required format: \"[Internal] Category: (Add|Fix|Refactor) Description\"<br /><br />
         Examples:<br />
         Diagnostics: Add GetElapsedClientLatency to CosmosDiagnostics<br/> 
         PartitionKey: Fix null reference when using default(PartitionKey)<br/> 
         [v4] Client Encryption: Refactor code to external project<br/>
         [Internal] Query: Add code generator for CosmosNumbers for easy additions in the future.<br/>
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
